name: Build and Run Docker for NASA Space Apps

# Trigger workflow on push to main branch or pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker (optional if using DockerHub)
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t nasa-ai .

      # Step 4: Run Docker container with OpenAI API key
      - name: Run Docker container
        run: docker run -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} nasa-ai
